###faça um programa que leia um numero inteiro qualquer e mostre na tela a sua tabuada
nu = int(input('Digite um numero para conferir sua tabuada: '))
print(nu *1, nu*2, nu*3, nu*4, nu*5, nu*6, nu*7, nu*8, nu*9, nu*10)
print('{} x {} = {}'.format(nu,1,nu*1))
print('{} x {} = {}'.format(nu,2,nu*2))     
print('{} x {} = {}'.format(nu,3,nu*3))
print('{} x {} = {}'.format(nu,4,nu*4))
print('{} x {} = {}'.format(nu,5,nu*5))
print('{} x {} = {}'.format(nu,6,nu*6))
print('{} x {} = {}'.format(nu,7,nu*7))
print('{} x {} = {}'.format(nu,8,nu*8))
print('{} x {} = {}'.format(nu,9,nu*9))
print('{} x {} = {}'.format(nu,10,nu*10))
