a = input('Digite algo: ')
print('O tipo primitivo desse valor é:',type(a))
print('É alfanumerico?',a.isalnum())
print('É composto só por espaços? ',a.isspace())
print('É do alfabeto? ',a.isalpha())
print('É decimal? ',a.isdecimal())
print('Está tudo em maiusculo? ',a.isupper())
print('Está tudo em minusculo? ',a.islower())
print('É numerico?',a.isnumeric())